### ISSUE TITLE
Procesos técnicos: front-end móvil

### ISSUE THREAD

**Issue by alexitoguiz** [UNIZAR-30226-2020-03/Flutter#9]
Describir los métodos, herramientas y técnicas necesarios tanto para construir el software (p.ej. herramientas de desarrollo) como para desplegarlo y probarlo (todos los necesarios para dar soporte a los planes descritos en la sección 3.2).

**Comment by alexitoguiz** [comment]
Cómo se construye e integra el software: si hay scripts de construcción automatizada o no (en ese caso qué se usa, y cómo se garantiza que todos los participantes compilan igual y con las mismas dependencias), qué se incluye en la construcción (descarga y actualización de dependencias, compilación, ejecución de tests automáticos...) y cada cuánto se construye (compila, integra, prueba) el sistema completo, cómo se configuran los computadores de los desarrolladores.
Cómo se despliega el software más allá de las máquinas de desarrollo: contenedores, máquinas virtuales, servidor en cloud etc. y cómo se configuran esos entornos (rutas, usuarios y contraseñas, puertos y otros elementos).

**Comment by SanTa45zgz** [comment]
Se ha actualizado la memoria con los procesos técnicos de la app móvil en el commit "vMemoriaGestionv6"
